# Generated by Django 5.0.1 on 2024-02-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_user_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='U2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.user')),
            ],
        ),
    ]
